#!/usr/bin/env node

/**
 * Setup Script para Migração Azure
 * 
 * Este script ajuda na configuração inicial do projeto para
 * desenvolvimento local e deploy no Azure Static Web Apps
 * 
 * Uso: node setup-azure.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function main() {
  console.log('\n🚀 EvolveAI Hackathon - Setup Azure Static Web Apps\n');
  console.log('Este script vai ajudá-lo a configurar o projeto para Azure.\n');

  const envPath = path.join(__dirname, '.env.local');
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    const overwrite = await question('⚠️  .env.local já existe. Deseja sobrescrever? (s/n): ');
    if (overwrite.toLowerCase() !== 's') {
      console.log('\n✅ Setup cancelado. Arquivo existente preservado.\n');
      rl.close();
      return;
    }
  }

  console.log('\n📋 Você precisa das credenciais do Firebase.\n');
  console.log('Para encontrá-las:');
  console.log('1. Acesse: https://console.firebase.google.com');
  console.log('2. Clique em seu projeto (evolveai-hackathon)');
  console.log('3. Vá em "Configurações" (ícone engrenagem)');
  console.log('4. Seção "Seus apps" → clique em Web app');
  console.log('5. Copie os valores abaixo\n');

  const apiKey = await question('VITE_FIREBASE_API_KEY: ');
  const authDomain = await question('VITE_FIREBASE_AUTH_DOMAIN: ');
  const projectId = await question('VITE_FIREBASE_PROJECT_ID: ');
  const storageBucket = await question('VITE_FIREBASE_STORAGE_BUCKET: ');
  const messagingSenderId = await question('VITE_FIREBASE_MESSAGING_SENDER_ID: ');
  const appId = await question('VITE_FIREBASE_APP_ID: ');

  const envContent = `# Firebase Configuration
# Generated by setup-azure.js
# IMPORTANTE: NÃO fazer commit deste arquivo!

VITE_FIREBASE_API_KEY=${apiKey}
VITE_FIREBASE_AUTH_DOMAIN=${authDomain}
VITE_FIREBASE_PROJECT_ID=${projectId}
VITE_FIREBASE_STORAGE_BUCKET=${storageBucket}
VITE_FIREBASE_MESSAGING_SENDER_ID=${messagingSenderId}
VITE_FIREBASE_APP_ID=${appId}
`;

  try {
    fs.writeFileSync(envPath, envContent);
    console.log('\n✅ .env.local criado com sucesso!\n');

    console.log('📝 Próximos passos:\n');
    console.log('1. Testar localmente:');
    console.log('   npm run dev\n');

    console.log('2. Configurar GitHub Secrets:');
    console.log('   - Vá para seu repositório no GitHub');
    console.log('   - Settings → Secrets and variables → Actions');
    console.log('   - Crie cada secret com os mesmos valores acima\n');

    console.log('3. Fazer commit:');
    console.log('   git add .');
    console.log('   git commit -m "fix: migração para Azure Static Web Apps"');
    console.log('   git push\n');

    console.log('4. Criar Static Web App no Azure:');
    console.log('   az staticwebapp create \\');
    console.log('     --name evolveai-hackathon-swa \\');
    console.log('     --resource-group evolveai-rg \\');
    console.log('     --source https://github.com/seu-usuario/seu-repo \\');
    console.log('     --location eastus\n');

    rl.close();
  } catch (error) {
    console.error('\n❌ Erro ao criar .env.local:', error.message, '\n');
    rl.close();
    process.exit(1);
  }
}

main();
